// The host artifact is bundled into a single JS file, so worker.py cannot be
// read from the plugin directory at runtime: it travels as a string and is
// written to the host's data directory on startup. This script regenerates
// that string from python/worker.py — the file that stays editable and
// testable on its own.
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const source = await readFile(join(root, "python", "worker.py"), "utf8");
const generated = `// Generated by scripts/embed-worker.mjs from python/worker.py — do not edit.
export const WORKER_SOURCE = ${JSON.stringify(source)};
`;
await writeFile(join(root, "src", "worker-source.ts"), generated);
console.log(`embedded python/worker.py (${source.length} bytes)`);
